"""Staging helpers: what to sync and what to exclude under ~/.pi/agent/."""

from __future__ import annotations

from pathlib import Path

# Paths under ~/.pi/agent/ that are NEVER synced.
#   npm/      regenerated by `pi install` from settings.json packages[]
#   bin/      arch-specific vendored binaries
#   sessions/ local per-machine session history
#   auth.json credentials (excluded by default; opt in via --with-auth)
EXCLUDED_DIRS: tuple[str, ...] = ("npm", "bin", "sessions")
EXCLUDED_FILES_DEFAULT: tuple[str, ...] = ("auth.json",)

AGENT_DIR_NAME = ".pi/agent"


def agent_dir() -> Path:
    """Return the pi agent config directory (~/.pi/agent/)."""
    return Path.home() / AGENT_DIR_NAME


def default_excludes(with_auth: bool = False) -> tuple[str, ...]:
    """fnmatch patterns excluded from sync.

    ``with_auth=True`` drops ``auth.json`` from the exclude list so credentials
    are included in the private bucket.
    """
    if with_auth:
        return EXCLUDED_DIRS
    return EXCLUDED_DIRS + EXCLUDED_FILES_DEFAULT
